# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  redis:
    #服务器地址
    host: 127.0.0.1
    #端口
    port: 6379
    #数据库索引，默认为0
    database: 0
    jedis:
      pool:
        #连接池最大连接数（负数表示没有限制）
        max-active: 50
        #连接池最大阻塞时间（负数表示没有限制）
        max-wait: 3000ms
        #连接池最大空闲数
        max-idle: 20
        #连接池最小空闲数
        min-idle: 5
    #连接超时时间
    timeout: 5000ms




